rootpath = "C:\\Users\\baudh\\OneDrive"
out_dir = "out"
ok_dir = "out/ok"
ko_dir = "out/ko"
kill_dir = "out/kill"
ffmpegpath = "C:\\dev\\videoshrink\\ffmpeg\\bin\\ffmpeg.exe"
ffprobepath = "C:\\dev\\videoshrink\\ffmpeg\\bin\\ffprobe.exe"
filetypes = ('avi', 'mp4', 'mkv', 'mpg', 'mpeg', 'avchd', 'mts', 'm2ts', 'm2t', 'wmv', 'mov', 'ogg')
maxbitrate_kbits = 4000
fileextension_out = 'mp4'
filesize_in_min_mb = 10
filesize_in_max_mb = 2000
